name: "Build Checks"

on:
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Activate Hermit
        run: |
          . ./bin/activate-hermit

      - name: Run tests
        run: ./bin/gradle test
