name: "Build Checks"
on:
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
      - name: Setup gradle
        uses: gradle/gradle-build-action@v2
      - name: Run tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
